name: C

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  tests:
    name: Build
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: registry.fedoraproject.org/fedora:34
          - os: macos-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install dependencies (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        # Actually a Fedora container
        dnf install -y \
          gcc make autoconf automake libtool pkg-config \
          zlib-devel \
          libpng-devel \
          libjpeg-turbo-devel \
          libtiff-devel \
          openjpeg2-devel \
          gdk-pixbuf2-devel \
          libxml2-devel \
          sqlite-devel \
          cairo-devel \
          glib2-devel \
          doxygen
    - name: Install dependencies (macOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install \
          gcc make autoconf automake libtool pkg-config \
          zlib \
          libpng \
          jpeg-turbo \
          libtiff \
          openjpeg \
          gdk-pixbuf \
          libxml2 \
          sqlite \
          cairo \
          glib
    - name: Build
      run: |
        autoreconf -i
        ./configure
        make -j4
    - name: Check exports
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: cd test && ./driver exports
  docs:
    name: Docs
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:34
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install tools
      run: dnf install -y doxygen
    - name: Build
      run: |
        basename=openslide-docs-$GITHUB_RUN_NUMBER-$(echo $GITHUB_SHA | cut -c-10)
        mkdir artifact
        cd doc
        doxygen
        mv html ../artifact/${basename}
        echo "basename=${basename}" >> $GITHUB_ENV
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.basename }}
        path: artifact
